# Generated by Django 4.2.24 on 2025-09-28 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=255)),
                ('ClassCode', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('YearLevel', models.CharField(max_length=50)),
                ('ScheduleDays', models.CharField(max_length=50)),
                ('ScheduleTime', models.TimeField()),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('InstructorID', models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.user')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Instructions', models.TextField()),
                ('DatePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateOfSubmission', models.DateTimeField()),
                ('ClassID', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.classinfo')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
