# Generated by Django 4.2.24 on 2025-09-08 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor')], max_length=10)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
