# Generated by Django 4.2.24 on 2025-09-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='PasswordHash',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='user_id',
        ),
    ]
