# Generated by Django 4.2.24 on 2025-10-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Department', models.CharField(max_length=100)),
                ('YearLevel', models.PositiveIntegerField()),
                ('ClassID', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.classinfo')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
