# Generated by Django 4.2.24 on 2025-09-10 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_datecreated_user_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('ClassID', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=255)),
                ('ClassCode', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('InstructorID', models.IntegerField()),
                ('YearLevel', models.CharField(max_length=50)),
                ('ScheduleDays', models.CharField(max_length=50)),
                ('ScheduleTime', models.TimeField()),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
    ]
