# Generated by Django 4.2.24 on 2025-09-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='InstructorID',
            field=models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
