# Generated by Django 4.2.24 on 2025-09-25 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_role_alter_classinfo_instructorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Instructions', models.TextField()),
                ('DatePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateOfSubmission', models.DateTimeField()),
                ('ClassID', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, to='api.classinfo')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Instructions', models.TextField()),
                ('DatePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateOfSubmission', models.DateTimeField()),
                ('ClassID', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, to='api.classinfo')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
