# Generated by Django 4.2.24 on 2025-09-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
